import { nanoid } from 'nanoid'
export const carsData = {
  make: {
    aston_martin: [
      {
        model: 'V12 Vantage',
        year: 2007,
        body: 'coupe',
        price: 97000,
        info: 'The original V12 Vantage concept was unveiled to guests at the opening of the Aston Martin Design Studio in December 2007. Continuing the marque’s impressive record of bringing concepts through to production, Aston Martin engineers brought V12 Vantage to market in a staggering 12 months.',
        condition: 'used',
        mileage: 128000,
        ref: nanoid(),
        src: 'https://images.pistonheads.com/nimg/44642/V12VantageS_10.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'navy green',
        sideImages: [
          'https://images.pistonheads.com/nimg/44642/V12VantageS_10.jpg',
          'https://image.vcars.co.uk/summit/3296159_3.jpg',
          'https://image.vcars.co.uk/summit/3296159_8.jpg',
          'https://image.vcars.co.uk/summit/3296159_10.jpg',
        ],
      },
      {
        model: 'V12 Vanquish',
        year: 2014,
        body: 'coupe',
        price: 129000,
        info: 'The unique features of the second generation Vanquish took the design ethos of Aston Martin into a new generation. The all-new exterior form was influenced by the One-77 supercar, seeing each carbon-fibre body panel take a taut, aggressive form.',
        condition: 'used',
        mileage: 75430,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/6-2017-aston-martin-vanquish-s-man-slide7-1527109001.jpg?crop=0.840xw:0.772xh;0.133xw,0.228xh&resize=1200:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'blue',
      },
      {
        model: 'V8 Vantage',
        year: 2021,
        body: 'coupe',
        price: 170000,
        info: 'The original V12 Vantage concept was unveiled to guests at the opening of the Aston Martin Design Studio in December 2007. Continuing the marque’s impressive record of bringing concepts through to production, Aston Martin engineers brought V12 Vantage to market in a staggering 12 months.',
        condition: 'new',
        mileage: 1000,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2020-aston-martin-vantage-amr-132-1571762595.jpg?crop=0.798xw:0.680xh;0.202xw,0.291xh&resize=1200:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'rose red',
      },
      {
        model: 'V8 Vantage Roadster',
        year: 2021,
        body: 'roadster',
        price: 183000,
        info: 'The original V12 Vantage concept was unveiled to guests at the opening of the Aston Martin Design Studio in December 2007. Continuing the marque’s impressive record of bringing concepts through to production, Aston Martin engineers brought V12 Vantage to market in a staggering 12 months.',
        condition: 'new',
        mileage: 1000,
        ref: nanoid(),
        src: 'https://cdn.motor1.com/images/mgl/oRwzl/s1/2021-aston-martin-vantage-roadster-exterior-front-quarter.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'nardo grey',
      },
    ],
    bentley: [
      {
        model: 'Continental GTC',
        year: 2007,
        body: 'roadster',
        price: 96000,
        info: 'The unique features of the second generation Vanquish took the design ethos of Aston Martin into a new generation. The all-new exterior form was influenced by the One-77 supercar, seeing each carbon-fibre body panel take a taut, aggressive form.',
        condition: 'used',
        mileage: 21300,
        ref: nanoid(),
        src: 'https://barrettjacksoncdn.azureedge.net/staging/carlist/items/Fullsize/Cars/223316/223316_Front_3-4_Web.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'black',
      },
      {
        model: 'Bentley Continental GT Speed',
        year: 2022,
        body: 'coupe',
        price: 308000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 300,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bentley-continental-gt-speed-2-1632854763.jpeg?crop=1.00xw:0.670xh;0,0.289xh&resize=980:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'red',
      },
      {
        model: 'Bentley Bentayga EWB V8 Azure',
        year: 2022,
        body: 'suv',
        price: 342000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 300,
        ref: nanoid(),
        src: 'https://thumbor.forbes.com/thumbor/fit-in/960x/https://www.forbes.com/wheels/wp-content/uploads/2022/09/2023_BentleyBentaygaEWBFD_1.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'light bronze',
      },
    ],
    jaguar: [
      {
        model: 'Jaguar F-Type',
        year: 2020,
        body: 'coupe',
        price: 71000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 8300,
        ref: nanoid(),
        src: 'https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191203042458_jaguar_f-type_front.jpg&w=700&q=90&c=1',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'blue metallic',
      },
      {
        model: 'Jaguar I-Pace',
        year: 2022,
        body: 'suv',
        price: 67000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 1300,
        ref: nanoid(),
        src: 'https://www.edmunds.com/assets/m/jaguar/i-pace/2020/oem/2020_jaguar_i-pace_4dr-hatchback_hse_fq_oem_1_815.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'blue metallic',
      },
      {
        model: 'Jaguar I-Pace',
        year: 2021,
        body: 'suv',
        price: 62000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 31300,
        ref: nanoid(),
        src: 'https://autobild.bg/wp-content/uploads/2019/03/jaguar-i-pace-lo-show-di-presentazione-dalle-19-del-1-marzo-768x432.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'soft grey',
      },
      {
        model: 'Jaguar XE',
        year: 2020,
        body: 'coupe',
        price: 139000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 300,
        ref: nanoid(),
        src: 'https://cdn.jdpower.com/JDPA_2020%20Jaguar%20XE%20R%20Dynamic%20S%20Red%20Front%20View.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'vibrant red',
      },
      {
        model: 'Jaguar F-Type',
        year: 2021,
        body: 'coupe',
        price: 84000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 100,
        ref: nanoid(),
        src: 'https://autonxt.net/wp-content/uploads/2022/02/2022-Jaguar-F-Type-P450-11-2048x1229.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'black',
      },
      {
        model: 'Jaguar F-Type',
        year: 2017,
        body: 'coupe',
        price: 64000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        src: 'https://i0.wp.com/www.retroclassiccar.com/wp-content/uploads/2022/03/WAXW7816-Copy.jpg?resize=1107%2C830&ssl=1',
        mileage: 12300,
        ref: nanoid(),
        color: 'alpine white',
      },
      {
        model: 'Jaguar F-Pace',
        year: 2021,
        body: 'suv',
        price: 68000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 1300,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2021-jaguar-f-pace-s-p400-152-1630522615.jpg?crop=0.716xw:0.602xh;0.248xw,0.362xh&resize=1200:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'blue metallic',
      },
    ],
    lamborghini: [
      {
        model: 'Lamborghini Urus',
        year: 2022,
        body: 'suv',
        price: 313000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 1300,
        ref: nanoid(),
        src: 'https://media.ed.edmunds-media.com/lamborghini/urus/2022/oem/2022_lamborghini_urus_4dr-suv_base_fq_oem_1_815.jpg',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'alpine white',
      },
      {
        model: 'Lamborghini Urus',
        year: 2020,
        body: 'suv',
        price: 228000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 11300,
        ref: nanoid(),
        transmission: 'automatic',
        src: 'https://media.ed.edmunds-media.com/lamborghini/urus/2022/oem/2022_lamborghini_urus_4dr-suv_base_fq_oem_2_815x543.jpg',
        engine: 'petrol',
        color: 'diablo yellow',
      },
      {
        model: 'Lamborghini Huracan Performante',
        year: 2021,
        body: 'coupe',
        price: 224000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 1300,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2020-lamborghini-huracan-evo-104-1576597210.jpg?crop=0.938xw:0.792xh;0.0619xw,0.208xh&resize=1200:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'nardo grey',
      },
      {
        model: 'Lamborghini Huracan Roadster',
        year: 2020,
        body: 'roadster',
        price: 214000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 700,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2021-lamborghini-huracan-evo-mmp-1-1600293029.jpg?crop=0.889xw:1.00xh;0.0561xw,0&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'snake green',
      },
      {
        model: 'Lamborghini Huracan Evo',
        year: 2021,
        body: 'coupe',
        price: 231000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 700,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2019-lamborghini-huracan-v10-106-1548279633.jpg?crop=0.893xw:1.00xh;0.107xw,0&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'fiery orange',
      },
      {
        model: 'Lamborghini Aventador LP-660',
        year: 2019,
        body: 'coupe',
        price: 247000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 17000,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2021-lamborghini-aventador-mmp-1-1601499002.jpg?crop=0.897xw:0.757xh;0.0753xw,0.173xh&resize=1200:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'red',
      },
    ],
    mclaren: [
      {
        model: 'McLaren 570s Spyder',
        year: 2020,
        body: 'roadster',
        price: 114000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 700,
        ref: nanoid(),
        transmission: 'automatic',
        engine: 'petrol',
        color: 'night blue',
      },
      {
        model: 'McLaren GT',
        year: 2021,
        body: 'coupe',
        price: 122000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 700,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2020-mclaren-gt-antonwatts-011-1585157522.jpg?crop=0.723xw:0.695xh;0.148xw,0.251xh&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'night blue',
      },
      {
        model: 'McLaren 600LT Spyder',
        year: 2019,
        body: 'roadster',
        price: 142000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 9700,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2019-mclaren-600lt-spider-102-1550610108.jpg?crop=0.893xw:1.00xh;0.0550xw,0&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'speed green',
      },
      {
        model: 'McLaren 720s',
        year: 2017,
        body: 'coupe',
        price: 148000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'used',
        mileage: 11200,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2018-mclaren-720s-1544821930.jpg?crop=0.816xw:1.00xh;0.0929xw,0&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'senna blue',
      },
      {
        model: 'McLaren 720s Spyder',
        year: 2020,
        body: 'roadster',
        price: 187000,
        info: 'An unprecedented flamboyant mix of different styles. And in all these styles, it excels like a real gentleman. Only the Bentley Continental GT Speed is capable of something that special. The Brit is full of luxury, charisma, sportiness and POWER. This unique example proves that these all go well together by combining its Front Seat Comfort Specification with Diamond Knurling and Styling Specification. That"s not all, because the endless option list with green check marks also mentions things such as ceramic brakes, Touring, City and Continental Blackline Specification. Furthermore, a combination of leather and Alcantara is “all over the place” inside. A beauty. A beast. And above all a wonderful offer from Prins, this Bentley GT Speed.',
        condition: 'new',
        mileage: 700,
        ref: nanoid(),
        src: 'https://hips.hearstapps.com/hmg-prod/images/2019-mclaren-720s-spider-390-1565493372.jpg?crop=0.617xw:0.751xh;0.0913xw,0.249xh&resize=640:*',
        transmission: 'automatic',
        engine: 'petrol',
        color: 'ocean blue',
      },
    ],
    rolls_royce: [],
  },
}
